<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Brand Color Palette - Universitas YPIB</title>
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- Vite / Tailwind -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        body { font-family: 'Plus Jakarta Sans', sans-serif; background-color: #F7F7F8; }
        .swatch-container {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(80px, 1fr));
            gap: 1rem;
            margin-top: 1rem;
        }
        .swatch {
            border-radius: 0.75rem;
            overflow: hidden;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
            transition: transform 0.2s ease-in-out;
        }
        .swatch:hover {
            transform: translateY(-4px);
        }
        .swatch-color {
            height: 80px;
            width: 100%;
        }
        .swatch-info {
            padding: 0.75rem;
            background: white;
            text-align: center;
        }
        .swatch-weight {
            font-weight: 700;
            font-size: 0.875rem;
            color: #181A20;
            margin-bottom: 0.25rem;
        }
        .swatch-hex {
            font-size: 0.75rem;
            color: #646E87;
            font-family: monospace;
            text-transform: uppercase;
        }
    </style>
</head>
<body class="text-[#181A20] antialiased min-h-screen pb-20">
    <div class="max-w-6xl mx-auto px-6 pt-16">
        <header class="mb-16">
            <div class="inline-flex items-center gap-3 px-4 py-2 bg-white rounded-full shadow-sm border border-[#E3E4E8] mb-6">
                <span class="w-3 h-3 rounded-full bg-[#0B41CB]"></span>
                <span class="text-sm font-semibold text-[#3B404F]">Design System Preview</span>
            </div>
            <h1 class="text-4xl md:text-5xl font-extrabold tracking-tight mb-4">Color Palette & Typography</h1>
            <p class="text-xl text-[#646E87] max-w-3xl leading-relaxed">
                Rekomendasi palet warna modern yang diekstrak secara harmonis dari warna biru dan kuning pada logo Universitas YPIB Majalengka.
            </p>
        </header>

        <!-- PRIMARY COLOR -->
        <section class="mb-16">
            <div class="flex items-end justify-between mb-2">
                <div>
                    <h2 class="text-2xl font-bold mb-1 flex items-center gap-2">
                        Primary <span class="px-2 py-1 bg-[#E5EBFA] text-[#0B41CB] text-xs rounded-md font-bold uppercase tracking-wider">Deep Navy Blue</span>
                    </h2>
                    <p class="text-[#646E87] text-sm">Digunakan untuk brand identity, header, tombol utama, dan teks penting.</p>
                </div>
            </div>
            
            <!-- Highlight Primary -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                <div class="bg-[#0B41CB] rounded-2xl p-8 text-white shadow-lg flex flex-col justify-between min-h-[160px]">
                    <div>
                        <div class="text-white/80 text-sm font-medium uppercase tracking-wider mb-1">Brand Primary</div>
                        <div class="text-3xl font-bold">Primary 600</div>
                    </div>
                    <div class="flex justify-between items-end">
                        <div class="font-mono text-xl">#0B41CB</div>
                        <div class="bg-white/20 px-3 py-1 rounded text-sm backdrop-blur-sm">WCAG AAA</div>
                    </div>
                </div>
                <div class="bg-[#09183E] rounded-2xl p-8 text-white shadow-lg flex flex-col justify-between min-h-[160px]">
                    <div>
                        <div class="text-white/80 text-sm font-medium uppercase tracking-wider mb-1">Dark Surface / Headings</div>
                        <div class="text-3xl font-bold">Primary 950</div>
                    </div>
                    <div class="flex justify-between items-end">
                        <div class="font-mono text-xl">#09183E</div>
                    </div>
                </div>
            </div>

            <div class="swatch-container">
                <!-- Swatches generated by UI Color Palette -->
                @php
                    $primary = [
                        '50' => '#F2F5FD', '100' => '#E5EBFA', '200' => '#C3D0F4',
                        '300' => '#91ADF2', '400' => '#5A83EC', '500' => '#0E4EF1',
                        '600' => '#0B41CB', '700' => '#0936A9', '800' => '#0B2B7F',
                        '900' => '#092367', '950' => '#09183E'
                    ];
                @endphp
                @foreach($primary as $weight => $hex)
                <div class="swatch">
                    <div class="swatch-color" style="background-color: {{ $hex }}"></div>
                    <div class="swatch-info">
                        <div class="swatch-weight">{{ $weight }}</div>
                        <div class="swatch-hex">{{ $hex }}</div>
                    </div>
                </div>
                @endforeach
            </div>
        </section>

        <!-- SECONDARY COLOR -->
        <section class="mb-16">
            <div class="flex items-end justify-between mb-2">
                <div>
                    <h2 class="text-2xl font-bold mb-1 flex items-center gap-2">
                        Secondary <span class="px-2 py-1 bg-[#FAF4E5] text-[#CB950B] text-xs rounded-md font-bold uppercase tracking-wider">Gold / Yellow</span>
                    </h2>
                    <p class="text-[#646E87] text-sm">Warna komplementer untuk aksen, highlight, notifikasi, dan elemen sekunder.</p>
                </div>
            </div>
            
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                <div class="bg-[#F1B10E] rounded-2xl p-8 text-white shadow-lg flex flex-col justify-between min-h-[160px]">
                    <div>
                        <div class="text-white/90 text-sm font-medium uppercase tracking-wider mb-1">Brand Secondary</div>
                        <div class="text-3xl font-bold text-[#3E2F09]">Secondary 500</div>
                    </div>
                    <div class="flex justify-between items-end text-[#3E2F09]">
                        <div class="font-mono text-xl">#F1B10E</div>
                    </div>
                </div>
            </div>

            <div class="swatch-container">
                @php
                    $secondary = [
                        '50' => '#FDFAF2', '100' => '#FAF4E5', '200' => '#F4E6C3',
                        '300' => '#F2D791', '400' => '#ECC35A', '500' => '#F1B10E',
                        '600' => '#CB950B', '700' => '#A97C09', '800' => '#7F5E0B',
                        '900' => '#674D09', '950' => '#3E2F09'
                    ];
                @endphp
                @foreach($secondary as $weight => $hex)
                <div class="swatch">
                    <div class="swatch-color" style="background-color: {{ $hex }}"></div>
                    <div class="swatch-info">
                        <div class="swatch-weight">{{ $weight }}</div>
                        <div class="swatch-hex">{{ $hex }}</div>
                    </div>
                </div>
                @endforeach
            </div>
        </section>

        <!-- NEUTRAL COLOR -->
        <section class="mb-16">
            <div class="flex items-end justify-between mb-2">
                <div>
                    <h2 class="text-2xl font-bold mb-1 flex items-center gap-2">
                        Neutrals <span class="px-2 py-1 bg-[#E3E4E8] text-[#4E566A] text-xs rounded-md font-bold uppercase tracking-wider">Cool Gray</span>
                    </h2>
                    <p class="text-[#646E87] text-sm">Abu-abu dengan rona kebiruan untuk teks body, border, dan background sekunder.</p>
                </div>
            </div>

            <div class="swatch-container">
                @php
                    $neutral = [
                        '50' => '#F7F7F8', '100' => '#F1F2F4', '200' => '#E3E4E8',
                        '300' => '#CDCFD6', '400' => '#9A9FAC', '500' => '#646E87',
                        '600' => '#4E566A', '700' => '#3B404F', '800' => '#272B35',
                        '900' => '#181A20', '950' => '#0D0E12'
                    ];
                @endphp
                @foreach($neutral as $weight => $hex)
                <div class="swatch">
                    <div class="swatch-color" style="background-color: {{ $hex }}"></div>
                    <div class="swatch-info">
                        <div class="swatch-weight">{{ $weight }}</div>
                        <div class="swatch-hex">{{ $hex }}</div>
                    </div>
                </div>
                @endforeach
            </div>
        </section>

        <!-- SEMANTIC COLORS -->
        <section class="mb-16">
            <div class="flex items-end justify-between mb-6">
                <div>
                    <h2 class="text-2xl font-bold mb-1 flex items-center gap-2">
                        Semantic Colors
                    </h2>
                    <p class="text-[#646E87] text-sm">Warna untuk mengkomunikasikan status dan notifikasi.</p>
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                <!-- Success -->
                <div class="bg-white rounded-2xl p-6 shadow-sm border border-[#E3E4E8]">
                    <div class="h-20 rounded-xl mb-4" style="background-color: #10B981"></div>
                    <div class="font-bold text-[#181A20] mb-1">Success</div>
                    <div class="font-mono text-sm text-[#646E87]">#10B981</div>
                </div>
                <!-- Warning -->
                <div class="bg-white rounded-2xl p-6 shadow-sm border border-[#E3E4E8]">
                    <div class="h-20 rounded-xl mb-4" style="background-color: #F59E0B"></div>
                    <div class="font-bold text-[#181A20] mb-1">Warning</div>
                    <div class="font-mono text-sm text-[#646E87]">#F59E0B</div>
                </div>
                <!-- Error -->
                <div class="bg-white rounded-2xl p-6 shadow-sm border border-[#E3E4E8]">
                    <div class="h-20 rounded-xl mb-4" style="background-color: #EF4444"></div>
                    <div class="font-bold text-[#181A20] mb-1">Error</div>
                    <div class="font-mono text-sm text-[#646E87]">#EF4444</div>
                </div>
                <!-- Info -->
                <div class="bg-white rounded-2xl p-6 shadow-sm border border-[#E3E4E8]">
                    <div class="h-20 rounded-xl mb-4" style="background-color: #3B82F6"></div>
                    <div class="font-bold text-[#181A20] mb-1">Info</div>
                    <div class="font-mono text-sm text-[#646E87]">#3B82F6</div>
                </div>
            </div>
        </section>

        <!-- GRADIENTS -->
        <section class="mb-16">
            <div class="flex items-end justify-between mb-6">
                <div>
                    <h2 class="text-2xl font-bold mb-1 flex items-center gap-2">
                        Brand Gradients
                    </h2>
                    <p class="text-[#646E87] text-sm">Gradasi warna elegan untuk background hero, ilustrasi, atau elemen dekoratif yang memberikan dimensi kedalaman.</p>
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                <!-- Deep Ocean (Primary Gradient) -->
                <div class="bg-white rounded-2xl p-6 shadow-sm border border-[#E3E4E8]">
                    <div class="h-32 rounded-xl mb-4 bg-gradient-to-br from-[#09183E] via-[#0B2B7F] to-[#0E4EF1]"></div>
                    <div class="font-bold text-[#181A20] mb-1">Deep Ocean</div>
                    <div class="font-mono text-xs text-[#646E87]">to-br from-Primary-950 to-Primary-500</div>
                </div>
                <!-- Golden Horizon (Secondary Gradient) -->
                <div class="bg-white rounded-2xl p-6 shadow-sm border border-[#E3E4E8]">
                    <div class="h-32 rounded-xl mb-4 bg-gradient-to-r from-[#CB950B] to-[#F2D791]"></div>
                    <div class="font-bold text-[#181A20] mb-1">Golden Horizon</div>
                    <div class="font-mono text-xs text-[#646E87]">to-r from-Secondary-600 to-Secondary-300</div>
                </div>
                <!-- Soft Sky (Light Gradient) -->
                <div class="bg-white rounded-2xl p-6 shadow-sm border border-[#E3E4E8]">
                    <div class="h-32 rounded-xl mb-4 bg-gradient-to-b from-[#E5EBFA] to-white border border-[#E3E4E8]"></div>
                    <div class="font-bold text-[#181A20] mb-1">Soft Sky</div>
                    <div class="font-mono text-xs text-[#646E87]">to-b from-Primary-100 to-white</div>
                </div>
            </div>
        </section>

        <!-- EXAMPLES IN ACTION -->
        <section>
            <h2 class="text-2xl font-bold mb-6">Contoh Komponen dengan Palet Baru</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
                <!-- Buttons Card -->
                <div class="bg-white p-8 rounded-2xl shadow-sm border border-[#E3E4E8]">
                    <h3 class="font-bold text-[#181A20] mb-6 border-b border-[#E3E4E8] pb-2">Buttons</h3>
                    <div class="space-y-4">
                        <button class="w-full py-3 px-4 bg-[#0B41CB] hover:bg-[#0936A9] text-white font-semibold rounded-xl transition">
                            Primary Button
                        </button>
                        <button class="w-full py-3 px-4 bg-[#F1B10E] hover:bg-[#CB950B] text-white font-semibold rounded-xl transition">
                            Secondary Accent Button
                        </button>
                        <button class="w-full py-3 px-4 bg-white hover:bg-[#F2F5FD] border border-[#C3D0F4] text-[#0B41CB] font-semibold rounded-xl transition">
                            Outline Button
                        </button>
                    </div>
                </div>

                <!-- Alert/Notification Card -->
                <div class="bg-white p-8 rounded-2xl shadow-sm border border-[#E3E4E8]">
                    <h3 class="font-bold text-[#181A20] mb-6 border-b border-[#E3E4E8] pb-2">Alerts & Cards</h3>
                    
                    <div class="bg-[#E5EBFA] border-l-4 border-[#0B41CB] p-4 rounded-r-xl mb-4">
                        <div class="flex items-start">
                            <div class="flex-shrink-0">
                                <svg class="h-5 w-5 text-[#0B41CB]" fill="currentColor" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"/>
                                </svg>
                            </div>
                            <div class="ml-3">
                                <p class="text-sm text-[#0936A9] font-medium">Informasi Penting</p>
                                <p class="text-sm text-[#0B41CB]/80 mt-1">Palet warna ini terlihat sangat profesional dan dapat dibaca dengan jelas.</p>
                            </div>
                        </div>
                    </div>

                    <div class="p-5 bg-white border border-[#E3E4E8] shadow-sm rounded-xl hover:border-[#91ADF2] transition cursor-pointer">
                        <div class="flex items-center justify-between mb-2">
                            <span class="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-[#FDFAF2] text-[#A97C09]">Program Favorit</span>
                            <span class="text-[#646E87] text-sm">2026</span>
                        </div>
                        <h4 class="text-lg font-bold text-[#09183E] mb-1">S1 Keperawatan</h4>
                        <p class="text-[#646E87] text-sm">Contoh bagaimana tipografi dan warna berpadu secara elegan pada sebuah card.</p>
                    </div>
                </div>
            </div>

            <!-- Forms & Inputs Card -->
            <div class="bg-white p-8 rounded-2xl shadow-sm border border-[#E3E4E8]">
                <h3 class="font-bold text-[#181A20] mb-6 border-b border-[#E3E4E8] pb-2">Forms & Inputs</h3>
                
                <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
                    <!-- Default State -->
                    <div>
                        <label class="block text-sm font-semibold text-[#3B404F] mb-2">Nama Lengkap</label>
                        <input type="text" placeholder="Masukkan nama..." class="w-full px-4 py-3 bg-white border border-[#E3E4E8] rounded-xl text-[#181A20] placeholder-[#9A9FAC] transition hover:border-[#9A9FAC] focus:outline-none focus:border-[#0B41CB] focus:ring-2 focus:ring-[#C3D0F4]">
                        <p class="mt-2 text-xs text-[#646E87]">Sesuai KTP atau ijazah terakhir.</p>
                    </div>

                    <!-- Focus State (Simulated) -->
                    <div>
                        <label class="block text-sm font-semibold text-[#3B404F] mb-2">Program Studi</label>
                        <select class="w-full px-4 py-3 bg-white border border-[#0B41CB] ring-2 ring-[#C3D0F4] rounded-xl text-[#181A20] focus:outline-none appearance-none">
                            <option>S1 Keperawatan</option>
                            <option>S1 Kesehatan Masyarakat</option>
                        </select>
                        <p class="mt-2 text-xs text-[#0B41CB] font-medium">State: Active / Focus</p>
                    </div>

                    <!-- Error State -->
                    <div>
                        <label class="block text-sm font-semibold text-[#3B404F] mb-2">Email Address</label>
                        <div class="relative">
                            <input type="email" value="email_salah.com" class="w-full px-4 py-3 bg-[#FEF2F2] border border-[#EF4444] rounded-xl text-[#B91C1C] focus:outline-none focus:border-[#EF4444] focus:ring-2 focus:ring-[#FEE2E2] pr-10">
                            <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                                <svg class="h-5 w-5 text-[#EF4444]" fill="currentColor" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </div>
                        <p class="mt-2 text-xs font-semibold text-[#DC2626]">Format email tidak valid.</p>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>
